version: '2'

services:
  db:
    image: mariadb:10
    environment:
      - "MYSQL_DATABASE=craft"
      - "MYSQL_USER=craft"
      - "MYSQL_PASSWORD=craft"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"

  php:
    image: jeffturcotte/php:latest
    environment:
      - "BOOTSTRAP=/bootstrap.sh"
      - "CRAFT_USERNAME=admin"
      - "CRAFT_EMAIL=info@imarc.com"
      - "CRAFT_SITENAME=Site"
      - "CRAFT_SITEURL=localhost"
      - "CRAFT_LOCALE=en_us"
    links:
      - db
    depends_on:
      - db
    volumes:
      - "./:/var/www/"
      - "./docker-bootstrap.sh:/bootstrap.sh"

  nginx:
    image: jeffturcotte/nginx-fastcgi:1
    ports:
      - "80:80"
    environment:
      - "NGINX_ROOT=/var/www/public"
    links:
      - php
    volumes:
      - "./:/var/www"
