version: '2'

services:
  db:
    image: mariadb:10
    environment:
      - "MYSQL_DATABASE=craft"
      - "MYSQL_USER=craft"
      - "MYSQL_PASSWORD=craft"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
    volumes:
        - "./.volumes/mysql:/var/lib/mysql"

  php:
    image: imarcagency/php-apache:1
    environment:
      - "APACHE_ROOT=/var/www/public"
    ports:
      - "80:80"
    links:
      - db
    depends_on:
      - db
    volumes:
      - "./:/var/www/"
      - "./.volumes/craft/storage:/var/www/craft/storage"
      - "./.volumes/craft/writable:/var/www/public/writable"
      - "./docker-bootstrap.sh:/opt/bootstrap"
